name    'example42-sysctl'
version '2.0.10'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-sysctl'
summary 'Puppet module for sysctl'
description 'This module installs and manages sysctl. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
